upstream api {
    server server:3000;
}

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 10m;

    location /auth/ {
        proxy_pass http://api;
        include /etc/nginx/snippets/proxy-api.conf;
    }

    location /accounts/ {
        proxy_pass http://api;
        include /etc/nginx/snippets/proxy-api.conf;
    }

    location /join/ {
        proxy_pass http://api;
        include /etc/nginx/snippets/proxy-api.conf;
    }

    location /bonus-buys/ {
        proxy_pass http://api;
        include /etc/nginx/snippets/proxy-api.conf;
    }

    location /prize-spins/ {
        proxy_pass http://api;
        include /etc/nginx/snippets/proxy-api.conf;
    }

    location /webhooks/ {
        proxy_pass http://api;
        include /etc/nginx/snippets/proxy-api.conf;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
