import type { BonusBuyRecord, BonusBuySlot } from '@/api/bonus-buy'

export type BonusBuyWidgetMock = {
  record: BonusBuyRecord
  slots: BonusBuySlot[]
}

const baseCreatedAt = '2026-09-16T10:00:00.000Z'

export const BONUS_BUY_WIDGET_MOCKS: Record<string, BonusBuyWidgetMock> = {
  '1': {
    record: {
      id: 1,
      accountId: 1,
      title: 'Friday stream',
      startBalance: '1000.00',
      isActive: true,
      createdAt: baseCreatedAt,
      createdByUserId: 1,
      createdByName: 'Operator',
    },
    slots: [
      {
        id: 1,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Sweet Bonanza 1000',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '152131.00',
        multiplier: '2535.52',
        isNowPlaying: true,
        createdAt: '2026-09-16T10:05:00.000Z',
      },
      {
        id: 2,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '53.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:10:00.000Z',
      },
      {
        id: 3,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '53.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:15:00.000Z',
      },
      {
        id: 4,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '53.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:20:00.000Z',
      },
      {
        id: 5,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '53.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:25:00.000Z',
      },
      {
        id: 6,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '531.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:25:00.000Z',
      },
      {
        id: 7,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '531.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:25:00.000Z',
      },
      {
        id: 8,
        bonusBuyId: 1,
        createdByUserId: 1,
        createdByName: 'Operator',
        slotName: 'Fist Of Destruction',
        nickProvider: 'Srednevekoviy',
        purchaseAmount: '60.00',
        winAmount: '531.40',
        multiplier: '0.89',
        isNowPlaying: false,
        createdAt: '2026-09-16T10:25:00.000Z',
      },
    ],
  },
}
